"""initial release schema

Revision ID: 374502cf2a83
Revises:
Create Date: 2026-07-19 02:28:27.306749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "374502cf2a83"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'suspended', 'deleted')", name="ck_tenant_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_index("ix_audit_tenant_created", "audit_events", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("legal_name", sa.String(length=240), nullable=False),
        sa.Column("normalized_name", sa.String(length=240), nullable=False),
        sa.Column("vat_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "normalized_name", name="uq_supplier_tenant_name"),
    )
    op.create_index(op.f("ix_suppliers_tenant_id"), "suppliers", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'reviewer', 'viewer')", name="ck_user_role"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_user_email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=True),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("number", sa.String(length=120), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("source_filename", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("mime_type", sa.String(length=150), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("parse_status", sa.String(length=30), nullable=False),
        sa.Column("parse_message", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("references_json", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "document_type IN ('order', 'confirmation', 'delivery', 'invoice', 'return', 'credit_note')",
            name="ck_document_type",
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "file_hash", name="uq_document_hash_per_tenant"),
    )
    op.create_index(
        "ix_document_tenant_supplier_type", "documents", ["tenant_id", "supplier_id", "document_type"], unique=False
    )
    op.create_index(op.f("ix_documents_supplier_id"), "documents", ["supplier_id"], unique=False)
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "item_aliases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=True),
        sa.Column("canonical_key", sa.String(length=280), nullable=False),
        sa.Column("alias", sa.String(length=280), nullable=False),
        sa.Column("normalized_alias", sa.String(length=280), nullable=False),
        sa.Column("confirmed_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "supplier_id", "normalized_alias", name="uq_item_alias"),
    )
    op.create_index(op.f("ix_item_aliases_tenant_id"), "item_aliases", ["tenant_id"], unique=False)
    op.create_table(
        "supplier_aliases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=240), nullable=False),
        sa.Column("normalized_alias", sa.String(length=240), nullable=False),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "normalized_alias", name="uq_supplier_alias"),
    )
    op.create_index(op.f("ix_supplier_aliases_supplier_id"), "supplier_aliases", ["supplier_id"], unique=False)
    op.create_index(op.f("ix_supplier_aliases_tenant_id"), "supplier_aliases", ["tenant_id"], unique=False)
    op.create_table(
        "document_lines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=280), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=120), nullable=True),
        sa.Column("size", sa.String(length=120), nullable=True),
        sa.Column("lot", sa.String(length=120), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("discount_rate", sa.Float(), nullable=False),
        sa.Column("tax_rate", sa.Float(), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("canonical_key", sa.String(length=500), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_lines_canonical_key"), "document_lines", ["canonical_key"], unique=False)
    op.create_index(op.f("ix_document_lines_document_id"), "document_lines", ["document_id"], unique=False)
    op.create_index(op.f("ix_document_lines_tenant_id"), "document_lines", ["tenant_id"], unique=False)
    op.create_index("ix_line_tenant_document", "document_lines", ["tenant_id", "document_id"], unique=False)
    op.create_table(
        "operation_chains",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_id", sa.String(length=36), nullable=True),
        sa.Column("order_document_id", sa.String(length=36), nullable=True),
        sa.Column("confirmation_document_id", sa.String(length=36), nullable=True),
        sa.Column("delivery_document_id", sa.String(length=36), nullable=True),
        sa.Column("invoice_document_id", sa.String(length=36), nullable=True),
        sa.Column("return_document_id", sa.String(length=36), nullable=True),
        sa.Column("credit_note_document_id", sa.String(length=36), nullable=True),
        sa.Column("reference_key", sa.String(length=280), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["confirmation_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["credit_note_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["delivery_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invoice_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["return_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chain_tenant_supplier", "operation_chains", ["tenant_id", "supplier_id"], unique=False)
    op.create_index(op.f("ix_operation_chains_reference_key"), "operation_chains", ["reference_key"], unique=False)
    op.create_index(op.f("ix_operation_chains_tenant_id"), "operation_chains", ["tenant_id"], unique=False)
    op.create_table(
        "chain_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("chain_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("match_reason", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('order', 'confirmation', 'delivery', 'invoice', 'return', 'credit_note')",
            name="ck_chain_document_role",
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["operation_chains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "document_id", name="uq_chain_document"),
    )
    op.create_index("ix_chain_document_role", "chain_documents", ["tenant_id", "chain_id", "role"], unique=False)
    op.create_index(op.f("ix_chain_documents_chain_id"), "chain_documents", ["chain_id"], unique=False)
    op.create_index(op.f("ix_chain_documents_document_id"), "chain_documents", ["document_id"], unique=False)
    op.create_index(op.f("ix_chain_documents_tenant_id"), "chain_documents", ["tenant_id"], unique=False)
    op.create_table(
        "discrepancy_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("chain_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("case_type", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("amount_estimate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("machine_generated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name="ck_case_severity"),
        sa.CheckConstraint(
            "status IN ('open', 'needs_review', 'confirmed', 'dismissed', 'resolved', 'superseded')",
            name="ck_case_status",
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["operation_chains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "fingerprint", name="uq_case_fingerprint"),
    )
    op.create_index(op.f("ix_discrepancy_cases_chain_id"), "discrepancy_cases", ["chain_id"], unique=False)
    op.create_index(op.f("ix_discrepancy_cases_tenant_id"), "discrepancy_cases", ["tenant_id"], unique=False)
    op.create_table(
        "evidence_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("document_line_id", sa.String(length=36), nullable=True),
        sa.Column("field_name", sa.String(length=120), nullable=False),
        sa.Column("observed_value", sa.Text(), nullable=True),
        sa.Column("expected_value", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["discrepancy_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_line_id"], ["document_lines.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_links_case_id"), "evidence_links", ["case_id"], unique=False)
    op.create_index(op.f("ix_evidence_links_tenant_id"), "evidence_links", ["tenant_id"], unique=False)
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('confirmed', 'dismissed', 'needs_review', 'resolved')", name="ck_review_decision"
        ),
        sa.ForeignKeyConstraint(["case_id"], ["discrepancy_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_decisions_case_id"), "review_decisions", ["case_id"], unique=False)
    op.create_index(op.f("ix_review_decisions_tenant_id"), "review_decisions", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_decisions_tenant_id"), table_name="review_decisions")
    op.drop_index(op.f("ix_review_decisions_case_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index(op.f("ix_evidence_links_tenant_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_case_id"), table_name="evidence_links")
    op.drop_table("evidence_links")
    op.drop_index(op.f("ix_discrepancy_cases_tenant_id"), table_name="discrepancy_cases")
    op.drop_index(op.f("ix_discrepancy_cases_chain_id"), table_name="discrepancy_cases")
    op.drop_table("discrepancy_cases")
    op.drop_index(op.f("ix_chain_documents_tenant_id"), table_name="chain_documents")
    op.drop_index(op.f("ix_chain_documents_document_id"), table_name="chain_documents")
    op.drop_index(op.f("ix_chain_documents_chain_id"), table_name="chain_documents")
    op.drop_index("ix_chain_document_role", table_name="chain_documents")
    op.drop_table("chain_documents")
    op.drop_index(op.f("ix_operation_chains_tenant_id"), table_name="operation_chains")
    op.drop_index(op.f("ix_operation_chains_reference_key"), table_name="operation_chains")
    op.drop_index("ix_chain_tenant_supplier", table_name="operation_chains")
    op.drop_table("operation_chains")
    op.drop_index("ix_line_tenant_document", table_name="document_lines")
    op.drop_index(op.f("ix_document_lines_tenant_id"), table_name="document_lines")
    op.drop_index(op.f("ix_document_lines_document_id"), table_name="document_lines")
    op.drop_index(op.f("ix_document_lines_canonical_key"), table_name="document_lines")
    op.drop_table("document_lines")
    op.drop_index(op.f("ix_supplier_aliases_tenant_id"), table_name="supplier_aliases")
    op.drop_index(op.f("ix_supplier_aliases_supplier_id"), table_name="supplier_aliases")
    op.drop_table("supplier_aliases")
    op.drop_index(op.f("ix_item_aliases_tenant_id"), table_name="item_aliases")
    op.drop_table("item_aliases")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_supplier_id"), table_name="documents")
    op.drop_index("ix_document_tenant_supplier_type", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_tenant_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index("ix_audit_tenant_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("tenants")
    # ### end Alembic commands ###
