"""add validation lab

Revision ID: 4c720e60d5f2
Revises: 374502cf2a83
Create Date: 2026-07-19 12:15:29.413478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c720e60d5f2"
down_revision: Union[str, Sequence[str], None] = "374502cf2a83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Widen canonical aliases before validation/matching enhancements use longer keys.
    with op.batch_alter_table("item_aliases") as batch_op:
        batch_op.alter_column(
            "canonical_key",
            existing_type=sa.String(length=280),
            type_=sa.String(length=500),
            existing_nullable=False,
        )
    op.create_table(
        "validation_datasets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("schema_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_validation_dataset_status"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", "version", name="uq_validation_dataset_version"),
    )
    op.create_index(op.f("ix_validation_datasets_tenant_id"), "validation_datasets", ["tenant_id"], unique=False)
    op.create_table(
        "validation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("engine_version", sa.String(length=40), nullable=False),
        sa.Column("scenario_count", sa.Integer(), nullable=False),
        sa.Column("true_positives", sa.Integer(), nullable=False),
        sa.Column("false_positives", sa.Integer(), nullable=False),
        sa.Column("false_negatives", sa.Integer(), nullable=False),
        sa.Column("precision", sa.Float(), nullable=False),
        sa.Column("recall", sa.Float(), nullable=False),
        sa.Column("f1_score", sa.Float(), nullable=False),
        sa.Column("amount_mae", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("gate_passed", sa.Boolean(), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name="ck_validation_run_status"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dataset_id"], ["validation_datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_validation_run_tenant_created", "validation_runs", ["tenant_id", "created_at"], unique=False)
    op.create_index(op.f("ix_validation_runs_dataset_id"), "validation_runs", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_validation_runs_tenant_id"), "validation_runs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_validation_runs_tenant_id"), table_name="validation_runs")
    op.drop_index(op.f("ix_validation_runs_dataset_id"), table_name="validation_runs")
    op.drop_index("ix_validation_run_tenant_created", table_name="validation_runs")
    op.drop_table("validation_runs")
    op.drop_index(op.f("ix_validation_datasets_tenant_id"), table_name="validation_datasets")
    op.drop_table("validation_datasets")
    with op.batch_alter_table("item_aliases") as batch_op:
        batch_op.alter_column(
            "canonical_key",
            existing_type=sa.String(length=500),
            type_=sa.String(length=280),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
