name: Publish Download Page

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "site/**"
      - ".github/workflows/pages.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.2.2
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # immutable upstream commit
      - uses: actions/upload-pages-artifact@98ef48e41587a300b82de4cf298aa98b57b2faae # immutable upstream commit
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # immutable upstream commit
